[workspace]
channels = ["conda-forge"]
name = "NSBI-workflow-tutorial"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"

[feature.gpu.system-requirements]
cuda = "12.5"

[feature.gpu.dependencies]
python = ">=3.12.11,<3.13"
jax = ">=0.5.2,<0.6"
tf2onnx = ">=1.16.1,<2"
scikit-learn = ">=1.7.1,<2"
pytables = ">=3.10.2,<4"
matplotlib-base = ">=3.10.5,<4"
mplhep = ">=0.4.1,<0.5"
numpy = ">=2.2.6,<3"
scipy = ">=1.16.1,<2"
pandas = ">=2.3.2,<3"
awkward = ">=2.8.7,<3"
pixi-kernel = ">=0.6.6,<0.7"
tensorflow-gpu = "2.18.*"
cuda-version = "12.6.*"
cudnn = "9.*"
onnx = ">=1.17.0,<2"
onnxruntime = ">=1.22.0,<2"
pyarrow = ">=19.0.1,<20"
coffea = ">=2025.7.3,<2026"

[feature.gpu.pypi-dependencies]
nsbi-common-utils = { path = ".", editable = true}

[feature.lab.dependencies]
notebook = "*"
jupyterlab = "*"
pixi-kernel = ">=0.6.6,<0.7"

[environments]
gpu = { features = ["gpu"], no-default-feature = true }
lab = { features = ["gpu", "lab"], no-default-feature = true }
